#!/usr/bin/env bash

info() {
	printf "\033[1;36m[INFO]\033[0m %s\n" "$@"
}

fatal() {
	printf "\033[1;31m[FATAL]\033[0m %s\n" "$@"
	exit 1
}

success() {
	printf "\033[1;32m[SUCCESS]\033[0m %s\n" "$@"
	exit 0
}

main() {
	local vm="inception"
	local vm_status=`VBoxManage showvminfo ${vm} --machinereadable | grep "VMState=" | cut -f 2 -d '"'`

	if [[ ${vm_status} != "running" ]]; then
		success "virtual machine is not running!"
	fi
	VBoxManage controlvm ${vm} acpipowerbutton || fatal "error occurred while shutting down vm"
	info "waiting for virtual machine to power off"
	until VBoxManage showvminfo ${vm} --machinereadable | grep 'VMState="poweroff"' >/dev/null
	do
		echo -n "."
		sleep 0.5
	done
	echo
	success "virtual machine is powered off"
}
main
