FROM alpine:3.23
RUN apk add --no-cache mariadb mariadb-client
# mariadb install should've created the mysql user, which is used by mariadb
# internally to do its thing in the /var/run/mysqld directory
RUN mkdir /var/run/mysqld \
	&& chown -R mysql:mysql /var/run/mysqld \
	&& chmod 777 /var/run/mysqld
EXPOSE 3306
COPY ./bootstrap_or_run.sh /
COPY ./mariadb-server.cnf /etc/my.cnf.d
CMD ["/bootstrap_or_run.sh"]
