FROM alpine:3.23
RUN apk update && apk add curl nginx
RUN adduser -D -g 'www' www
RUN mkdir /www && \
	chown -R www:www /var/lib/nginx && \
	chown -R www:www /www
COPY ./nginx.conf /etc/nginx/nginx.conf
CMD [ "nginx", "-g", "daemon off;" ]
