FROM alpine:3.23
RUN apk add --no-cache curl nginx
# nginx user + ownership
RUN adduser -D -g 'www' www && chown -R www:www /var/lib/nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
# foreground nginx process
CMD [ "nginx", "-g", "daemon off;" ]
