FROM alpine:3.23
RUN apk update
RUN apk add curl
RUN apk add nginx
RUN adduser -D -g 'www' www
RUN mkdir /www && \
	chown -R www:www /var/lib/nginx && \
	chown -R www:www /www
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /www/index.html
CMD [ "nginx", "-g", "daemon off;" ]
