FROM alpine:3.23
RUN apk add --no-cache php84-fpm php84-mysqli php84 php84-phar php84-iconv mysql-client php84-openssl
RUN wget -q https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp

EXPOSE 9000
COPY www.conf /etc/php84/php-fpm.d/www.conf
COPY php.ini /etc/php84/php.ini
COPY run_or_bootstrap.sh /
CMD [ "/run_or_bootstrap.sh" ]
